only_rules:
  - accessibility_label_for_image
  - accessibility_trait_for_button

# Configure the rules
accessibility_label_for_image:
  severity: error

accessibility_trait_for_button:
  severity: error
