only_rules:
  - accessibility_label_for_image
  - accessibility_trait_for_button
  - a11y_swiftui_image_missing_label
  - a11y_button_missing_label
  - a11y_empty_text

# Configure the rules
accessibility_label_for_image:
  severity: error

accessibility_trait_for_button:
  severity: error

# Define your custom a11y rules
custom_rules:
  a11y_swiftui_image_missing_label:
    name: "SwiftUI Image Missing Accessibility Label"
    regex: "\\bImage\\((?!.*accessibilityLabel)(?!.*\\.accessibilityElement\\(children: \\.combine\\))"
    message: "SwiftUI Image needs accessibilityLabel() or .accessibilityHidden(true), unless using .accessibilityElement(children: .combine)"
    severity: error
  
  a11y_button_missing_label:
    name: "SwiftUI Button Missing Accessibility Label"
    regex: "Button\\s*\\{[^}]*\\}\\s*(?!.*accessibilityLabel)"
    message: "SwiftUI Button must have accessibilityLabel() or visible text."
    severity: error
  
  a11y_empty_text:
    name: "Empty Text() is bad for accessibility"
    regex: "Text\\([\"']{2}\\)"
    message: "Empty Text() is not accessible — use hidden or provide a label."
    severity: error
