import SwiftUI

struct Techniques: Identifiable {
    let id = UUID()
    let name: String
}

let techniques: [Techniques] = [
    // Techniques(name: "Accessibility Hidden"),
    // Techniques(name: "Accessibility Notifications"),
    // Techniques(name: "Accessibility Identifier"),
    // Techniques(name: "Accessibility Representation"),
    // Techniques(name: "Accessibility Responds To User Interaction"),
    // Techniques(name: "Accessibility Sort Priority"),
    // Techniques(name: "Accessibility Actions"),
    // Techniques(name: "Accordions"),
    // Techniques(name: "Adjustable Action"),
    // Techniques(name: "Alerts"),
    // Techniques(name: "Accessibility Detection"),
    // Techniques(name: "Attributed Strings"),
    Techniques(name: "Assistive Access"),
    Techniques(name: "Buttons"),
    // Techniques(name: "Cards"),
    // Techniques(name: "Charts"),
    // Techniques(name: "Carousels"),
    Techniques(name: "Checkboxes"),
    // Techniques(name: "Combining Focus"),
    // Techniques(name: "Confirmation Dialogs"),
    // Techniques(name: "Dark Mode"),
    // Techniques(name: "Data Tables"),
    Techniques(name: "Date & Time Pickers"),
    // Techniques(name: "Decorative Images"),
    Techniques(name: "Device Orientation"),
    Techniques(name: "Dynamic Type"),
    // Techniques(name: "Error Validation"),
    // Techniques(name: "Escape Action"),
    // Techniques(name: "Focus Management"),
    // Techniques(name: "Functional Images"),
    // Techniques(name: "Grouping Controls"),
    // Techniques(name: "Headings"),
    // Techniques(name: "Horizontal Scroll Views"),
    // Techniques(name: "Increase Contrast"),
    Techniques(name: "Informative Images"),
    // Techniques(name: "Input Instructions"),
    // Techniques(name: "Accessibility Input Labels"),
    // Techniques(name: "Language"),
    // Techniques(name: "Large Content Viewer"),
    Techniques(name: "Links"),
    // Techniques(name: "Lists"),
    // Techniques(name: "Magic Tap"),
    // Techniques(name: "Maps"),
    // Techniques(name: "Meaningful Accessible Names"),
    // Techniques(name: "Menus"),
    // Techniques(name: "Navigation"),
    // Techniques(name: "Page Titles"),
    Techniques(name: "Pickers"),
    Techniques(name: "Popovers"),
    Techniques(name: "Progress Indicators"),
    // Techniques(name: "Prototypes"),
    Techniques(name: "Radio Buttons"),
    // Techniques(name: "Reading Order"),
    // Techniques(name: "Reduce Motion"),
    // Techniques(name: "Reduce Transparency"),
    // Techniques(name: "Redundant Entry"),
    // Techniques(name: "Responsive Layouts"),
    // Techniques(name: "Accessibility Rotor"),
    // Techniques(name: "Scroll Views"),
    // Techniques(name: "Search Suggestions"),
    // Techniques(name: "Segmented Controls"),
    Techniques(name: "Sheets"),
    Techniques(name: "Sliders"),
    // Techniques(name: "Smart Invert"),
    Techniques(name: "Steppers"),
    Techniques(name: "Tabs"),
    Techniques(name: "Text Fields"),
    Techniques(name: "Toggles"),
    Techniques(name: "Videos"),
    Techniques(name: "Touch Target Size"),
    // Techniques(name: "VoiceOver Announcement Delay"),
    // Techniques(name: "VoiceOver Pronunciation")
]
